/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanjava;


import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author AD
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    DBConnection dbconnect;
    public LogIn() {
        initComponents();
        dbconnect = new DBConnection();
        if(dbconnect == null){
            JOptionPane.showMessageDialog(this, "Database không thể kết nối", "Error !", JOptionPane.ERROR_MESSAGE);
        }           
        
        lblUsername.setVisible(false);
        lblPassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnSignin = new javax.swing.JButton();
        jlforgetPassword = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setBackground(new java.awt.Color(255, 153, 153));
        setForeground(new java.awt.Color(255, 153, 153));
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Log In");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 20, 140, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 80, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 170, 80, 25);

        btnRegister.setBackground(new java.awt.Color(255, 102, 153));
        btnRegister.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(220, 220, 120, 30);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(160, 82, 420, 30);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(160, 170, 420, 30);

        btnSignin.setBackground(new java.awt.Color(255, 102, 153));
        btnSignin.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        btnSignin.setForeground(new java.awt.Color(255, 255, 255));
        btnSignin.setText("Submit");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignin);
        btnSignin.setBounds(380, 220, 110, 30);

        jlforgetPassword.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jlforgetPassword.setForeground(new java.awt.Color(255, 0, 0));
        jlforgetPassword.setText("Forget password");
        jlforgetPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlforgetPasswordMouseMoved(evt);
            }
        });
        jlforgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlforgetPasswordMousePressed(evt);
            }
        });
        getContentPane().add(jlforgetPassword);
        jlforgetPassword.setBounds(270, 310, 150, 23);

        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanjava/Images/warning.png"))); // NOI18N
        getContentPane().add(lblPassword);
        lblPassword.setBounds(580, 170, 50, 48);

        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doanjava/Images/warning.png"))); // NOI18N
        getContentPane().add(lblUsername);
        lblUsername.setBounds(580, 80, 50, 48);
        getContentPane().add(panel);
        panel.setBounds(-10, 0, 760, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        dispose();
        RegisterAccount rgc= new RegisterAccount();
        rgc.setTitle("Register page");
        rgc.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        // TODO add your handling code here:
        lblUsername.setVisible(false);
        lblPassword.setVisible(false);
        
        String username= txtUsername.getText();
        String password= String.valueOf(txtPassword.getPassword());
        if(username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Username/Password không nên trống", "Error !", JOptionPane.ERROR_MESSAGE);
        }else{
            userLogin(username, password);
        }
        
        if(txtUsername.getText().equals("")){
            lblUsername.setVisible(true);
        }
        if(String.valueOf(txtPassword.getPassword()).equals("")){
            lblPassword.setVisible(true);
        }
        
        
    }//GEN-LAST:event_btnSigninActionPerformed

    private void jlforgetPasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlforgetPasswordMouseMoved
        // TODO add your handling code here:
        jlforgetPassword.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jlforgetPasswordMouseMoved

    private void jlforgetPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlforgetPasswordMousePressed
        // TODO add your handling code here:
        SendCode sc= new SendCode();
        this.setVisible(false);
        sc.setVisible(true);
    }//GEN-LAST:event_jlforgetPasswordMousePressed
    private void userLogin(String username, String password) {
        Connection conDB = DBConnection.connectDB();
        if(conDB!=null){
            try {
                PreparedStatement st= (PreparedStatement)conDB.prepareStatement("Select * from register_account_qlhv where username=? and password=? ") ;
                
                st.setString(1, username);
                st.setString(2, password);
                ResultSet res= st.executeQuery();
                if(res.next()){
                    
                    PageHome ph= new PageHome();
                    ph.setTitle("Page home");
                    ph.setVisible(true);
                    PageHome.lblStudents.setText("Account join= \t"+Integer.toString(MyFunction.countData("user")) );
                   
                    dispose();
                }else{
                    System.out.println("username" +username);
                    System.out.println("password" +password);
                    JOptionPane.showMessageDialog(this, "Username/Password không tìm thấy", "Error !", JOptionPane.ERROR_MESSAGE);
                }
            }catch (SQLException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.out.println("Không thể kết nối database!");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnRegister;
    javax.swing.JButton btnSignin;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jlforgetPassword;
    javax.swing.JLabel lblPassword;
    javax.swing.JLabel lblUsername;
    javax.swing.JLabel panel;
    javax.swing.JPasswordField txtPassword;
    public static javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
}
