/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanjava;

/**
 *
 * @author AD
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics;
public class PageHome extends javax.swing.JFrame {

    /**
     * Creates new form PageHome
     */
    public PageHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im=new ImageIcon("school.png");
                Image i=im.getImage();

                g.drawImage(i, 0, 0, this.getSize().height, this.getSize().width, this);
            }
        };
        jPanel5 = new javax.swing.JPanel();
        btnDangkihocvien = new javax.swing.JButton();
        btnQuanlyhocvien = new javax.swing.JButton();
        btnBaocao = new javax.swing.JButton();
        btnBangdiem = new javax.swing.JButton();
        btnDangkimonhoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Page home");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 102, 0));

        btnDangkihocvien.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDangkihocvien.setText("Đăng kí học viên");
        btnDangkihocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkihocvienActionPerformed(evt);
            }
        });

        btnQuanlyhocvien.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnQuanlyhocvien.setText("Quản lý học viên");
        btnQuanlyhocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlyhocvienActionPerformed(evt);
            }
        });

        btnBaocao.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnBaocao.setText("Báo cáo");
        btnBaocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaocaoActionPerformed(evt);
            }
        });

        btnBangdiem.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnBangdiem.setText("Bảng điểm");
        btnBangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangdiemActionPerformed(evt);
            }
        });

        btnDangkimonhoc.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDangkimonhoc.setText("Đăng kí môn học");
        btnDangkimonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkimonhocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBangdiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBaocao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanlyhocvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangkihocvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangkimonhoc))
                .addGap(131, 131, 131))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnQuanlyhocvien)
                .addGap(18, 18, 18)
                .addComponent(btnDangkihocvien)
                .addGap(13, 13, 13)
                .addComponent(btnBangdiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBaocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDangkimonhoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanlyhocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlyhocvienActionPerformed
        // TODO add your handling code here:
        QuanLyHocVien quanly=new QuanLyHocVien();
        quanly.setVisible(true);
        quanly.setTitle("Quản ly học viên");
        dispose();
    }//GEN-LAST:event_btnQuanlyhocvienActionPerformed

    private void btnDangkihocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkihocvienActionPerformed
        // TODO add your handling code here:
        DangKiHocVien dkhv=new DangKiHocVien();
        dkhv.setVisible(true);
        dkhv.setTitle("Đăng kí học viên");
        dispose();
    }//GEN-LAST:event_btnDangkihocvienActionPerformed

    private void btnDangkimonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkimonhocActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDangkimonhocActionPerformed

    private void btnBangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangdiemActionPerformed
        // TODO add your handling code here:
        BangDiem bd=new BangDiem();
        bd.setVisible(true);
        bd.setTitle("Bảng điểm");
        dispose ();
    }//GEN-LAST:event_btnBangdiemActionPerformed

    private void btnBaocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaocaoActionPerformed
        // TODO add your handling code here:
        BaoCao bc=new BaoCao();
        bc.setVisible(true);
        bc.setTitle("Báo cáo");
        dispose();
    }//GEN-LAST:event_btnBaocaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBangdiem;
    private javax.swing.JButton btnBaocao;
    private javax.swing.JButton btnDangkihocvien;
    private javax.swing.JButton btnDangkimonhoc;
    private javax.swing.JButton btnQuanlyhocvien;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
